/**
 * External Dependencies.
 */
import { MRT_RowData, createMRTColumnHelper } from "material-react-table";

const columnHelper = createMRTColumnHelper<MRT_RowData>();

export const columns = [
  columnHelper.accessor("id", {
    header: "ID",
    size: 20,
  }),
  columnHelper.accessor("symbol", {
    header: "Symbol",
    size: 40,
  }),
  columnHelper.accessor("name", {
    header: "Name",
    size: 240,
  }),
  columnHelper.accessor("open", {
    header: "Open",
    size: 100,
  }),
  columnHelper.accessor("high", {
    header: "High",
    size: 100,
  }),
  columnHelper.accessor("low", {
    header: "Low",
    size: 100,
  }),
  columnHelper.accessor("close", {
    header: "Close",
    size: 100,
  }),
  columnHelper.accessor("volume", {
    header: "Volume",
    size: 100,
  }),
];

export const topTurnover = [
  {
    id: 1,
    symbol: "Turnover",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 2,
    symbol: "Turnover",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 3,
    symbol: "Turnover",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 4,
    symbol: "Turnover",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 5,
    symbol: "Turnover",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 6,
    symbol: "Turnover",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 7,
    symbol: "Turnover",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 8,
    symbol: "Turnover",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 9,
    symbol: "Turnover",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 10,
    symbol: "Turnover",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
] as MRT_RowData[];

export const topLoser = [
  {
    id: 1,
    symbol: "Loser",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 2,
    symbol: "Loser",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 3,
    symbol: "Loser",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 4,
    symbol: "Loser",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 5,
    symbol: "Loser",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 6,
    symbol: "Loser",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 7,
    symbol: "Loser",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 8,
    symbol: "Loser",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 9,
    symbol: "Loser",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 10,
    symbol: "Loser",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
] as MRT_RowData[];

export const topGainer = [
  {
    id: 1,
    symbol: "Gainer",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 2,
    symbol: "Gainer",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 3,
    symbol: "Gainer",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 4,
    symbol: "Gainer",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 5,
    symbol: "Gainer",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 6,
    symbol: "Gainer",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 7,
    symbol: "Gainer",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 8,
    symbol: "Gainer",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 9,
    symbol: "Gainer",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
  {
    id: 10,
    symbol: "Gainer",
    name: "Wilkinson",
    open: 20,
    high: 20,
    low: 20,
    close: 20,
    volume: 20,
  },
] as MRT_RowData[];
